spring:
  application:
    name: doctor
  profiles:
    include: shared
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

  mail:
    host: ${SPRING_MAIL_QQ_HOST} # smtp.qq.com
    username: ${SPING_MAIL_QQ_USER} # 1656426916@qq.com
    password: ${SPRING_MAIL_QQ_PAW} # ligrpqhgjqrjejjf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
        debug: true

server:
  port: 9091

weather:
  api:
    url: https://cn.apihz.cn/api/tianqi/tqyb.php
    key: 88888888
    id: 88888888

ollama:
  api:
    url: http://localhost:11434/api/generate
    medel: qwen2:7b

anything-llm:
  url: http://localhost:8180
  workspace: hospital

aliyun:
  sms:
    access-key-id-env: OSS_ACCESS_KEY_ID
    access-key-secret-env: OSS_ACCESS_KEY_SECRET
    sign-name: 熙心健康体检
    REGION_ID: cn-shanghai
    PRODUCT: Dysmsapi
    DOMAIN: dysmsapi.aliyuncs.com
    template-code:
      report: SMS_468195539
      tip: SMS_468320452
