spring:
  application:
    name: user
  profiles:
    include: shared
  data:
    redis:
      host: ${RDS_REDIS_HOST:localhost}
      port: ${RDS_REDIS_PORT:6379}
      password: ${RDS_REDIS_PASSWORD}
      repositories:
        enabled: false
  lettuce:
    pool:
      max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 5 # 连接池中的最小空闲连接
      max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

server:
  port: 9092
