spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_DB_HOST:localhost}:3306/project-test?allowMultiQueries=true
    username: ${RDS_DB_USER:root}
    password: ${RDS_DB_PASS:root}
  jpa:
    show-sql: true

  # Json 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  ############## sa-token 配置 文档: https://sa-token.cc/doc.html#/use/config
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token前缀
  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: ${JWT_SECRET_KEY:iamthestormthatisapproachingwryyyyyyy}
  # 是否输出操作日志
  is-log: true

# 日志配置
logging:
  level:
    root: info
    me.qunqun: debug

# 文档配置
springdoc:
  api-docs:
    enabled: true
    #open api 文档访问路径
    path: /api/docs
  swagger-ui:
    enabled: true
    #swagger-ui 访问路径
    path: /api/docs/ui

